// src/components/Nav.vue
<template>
    <header class="fixed w-full z-20 top-0 left-0 border-b border-gray-700 bg-gray-900">
        <nav class="bg-gray-900 px-4 py-4 mx-auto max-w-screen-xl flex justify-between items-center">
            <a href="/"><img src="src/assets/logo.svg" class="w-40 md:w-56" /></a>
            <div class="flex gap-2">
                <a href="/tickets" class="text-xs px-2 md:px-3 py-2 text-center text-white bg-bbblue rounded-md hover:bg-bblightblue ring-1 ring-bblightblue hover:ring-bblightblue">Ticket info</a>
            </div>
        </nav>
    </header>
</template>

<script>
export default {
    
}
</script>

<style>
    
</style>

// src/lib/Nav.svelte
<header class="fixed w-full z-20 top-0 left-0 border-b border-gray-700 bg-gray-900">
    <nav class="bg-gray-900 px-4 py-4 mx-auto max-w-screen-xl flex justify-between items-center">
        <a href="/"><img src="logo.svg" class="w-40 md:w-56" alt="logo" /></a>
        <div class="flex gap-2">
            <a href="/tickets" class="text-xs px-2 md:px-3 py-2 text-center text-white bg-bbblue rounded-md hover:bg-bblightblue ring-1 ring-bblightblue hover:ring-bblightblue">Ticket info</a>
        </div>
    </nav>
</header>
