// src/lib/Footer.svelte
<hr class="mb-6 border-gray-800 sm:mx-auto dark:border-gray-700" />

<footer class="p-4 sm:p-6 mx-auto max-w-screen-xl">
    <div class="md:flex md:justify-between">

        <!-- logo -->
        <div class="mb-6 md:mb-0">
            <a href="/" class="flex items-center"><img src="../logo.svg" class="h-8 mr-3" alt="Budget Broadway Logo" /></a>
        </div>
        
        <!-- links -->
        <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-2">
            <div class="text-sm">
                <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Shows</h2>
                <ul class="text-gray-500">
                    <li class="mb-4"><a href="https://www.broadway.org/shows" class="hover:text-white">Broadway.org</a></li>
                    <li><a href="https://www.ibdb.com/" class="hover:text-white">IBDB</a></li>
                </ul>
            </div>
            <div class="text-sm">
                <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Tickets</h2>
                <ul class="text-gray-500">
                    <li class="mb-4"><a href="https://www.seatgeek.com/" class="hover:text-white">SeatGeek</a></li>
                    <li class="mb-4"><a href="https://www.telecharge.com/" class="hover:text-white">Telecharge</a></li>
                    <li><a href="https://www.ticketmaster.com/" class="hover:text-white">Ticketmaster</a></li>
                </ul>
            </div>
        </div>
    </div>

    <hr class="my-6 border-gray-800 sm:mx-auto dark:border-gray-700 lg:my-8" />

    <!-- copyright -->
    <div class="sm:flex sm:items-center sm:justify-between">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="/" class="hover:text-white">Budget Broadway</a>. All Rights Reserved.
        </span>
    </div>
</footer>

// src/components/Footer.vue
<template>
    <hr class="mb-6 border-gray-800 sm:mx-auto dark:border-gray-700" />

    <footer class="p-4 sm:p-6 mx-auto max-w-screen-xl">
        <div class="md:flex md:justify-between">

            <!-- logo -->
            <div class="mb-6 md:mb-0">
                <a href="/" class="flex items-center"><img src="src/assets/logo.svg" class="h-8 mr-3" alt="Budget Broadway Logo" /></a>
            </div>
            
            <!-- links -->
            <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-2">
                <div class="text-sm">
                    <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Shows</h2>
                    <ul class="text-gray-500">
                        <li class="mb-4"><a href="https://www.broadway.org/shows" class="hover:text-white">Broadway.org</a></li>
                        <li><a href="https://www.ibdb.com/" class="hover:text-white">IBDB</a></li>
                    </ul>
                </div>
                <div class="text-sm">
                    <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Tickets</h2>
                    <ul class="text-gray-500">
                        <li class="mb-4"><a href="https://www.seatgeek.com/" class="hover:text-white">SeatGeek</a></li>
                        <li class="mb-4"><a href="https://www.telecharge.com/" class="hover:text-white">Telecharge</a></li>
                        <li><a href="https://www.ticketmaster.com/" class="hover:text-white">Ticketmaster</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <hr class="my-6 border-gray-800 sm:mx-auto dark:border-gray-700 lg:my-8" />

        <!-- copyright -->
        <div class="sm:flex sm:items-center sm:justify-between">
            <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="/" class="hover:text-white">Budget Broadway</a>. All Rights Reserved.
            </span>
        </div>
    </footer>
</template>

<script>
export default {

}
</script>

<style>

</style>
