// src/lib/ShowCard.svelte
<script>
    export let show

    function getImageUrl(show) {
        return `${show.location.replaceAll(".", "").split(" ").join("")}.jpg`
    }
</script>

<div class="items-center bg-gray-800 border border-gray-700 rounded-md flex">
    <img class="w-28 rounded-md" src={`playbills/${getImageUrl(show)}`} alt={show.name} />
    <div class="p-5 text-sm">
        <h2 class="text-base font-bold text-white">{show.name}</h2>
        <p>{show.location} Theater</p>
        <p>{show.address}</p>
        {#if show.closes}
            <p class="text-bbblue font-bold">Closes {show.closes.replaceAll("-", "/")}</p>
        {/if}
    </div>
</div>

// src/components/ShowCard.jsx
function ShowCard({show}) {
    function getImageUrl(show) {
        return `src/assets/images/playbills/${show.location.replaceAll(".", "").split(" ").join("")}.jpg`
    }
    
    return (
        <div className="items-center bg-gray-800 border-gray-700 rounded-md shadow sm:flex">
            <img className="w-28" src={getImageUrl(show)} alt={show.name} />
            <div className="p-5">
                <h3 className="text-xl font-bold text-white">{show.name}</h3>
                <p>{show.location} Theater</p>
                <p>{show.address}</p>
                {show.closes && <p className="text-bbblue font-bold">Closes {show.closes.replaceAll("-", "/")}</p>}

                <ul className="flex space-x-4 mt-4">
                    <li>
                        <a href="#" className="px-3 py-2 text-sm font-bold text-center text-white bg-gray-700 rounded-lg hover:bg-gray-600 ring-1 ring-gray-600 hover:ring-gray-500">Discount</a>
                    </li>
                    <li>
                        <a href="#" className="px-3 py-2 text-sm font-bold text-center text-white bg-gray-700 rounded-lg hover:bg-gray-600 ring-1 ring-gray-600 hover:ring-gray-500">Discount</a>
                    </li>
                </ul>
            </div>
        </div>
    )
}

export default ShowCard
