// src/App.jsx
import { BrowserRouter as Router, Route, Routes } from "react-router-dom"
import Nav from "./Nav"
import Home from "./Home"
import Rush from "./Rush"

function App() {
    return (
        <Router>
            <div className="App">
                <Nav />
                <main className="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
                    <Routes>
                        <Route path="/" element={<Home />} />
                        <Route path="/rush" element={<Rush />} />
                    </Routes>
                </main>
            </div>
        </Router>
    )
}

export default App

// src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
import Nav from './components/Nav.vue';
import Footer from './components/Footer.vue';
</script>

<template>
    <Nav />
    <main class="mx-auto max-w-screen-xl lg:py-16 lg:px-6">
        <RouterView />
    </main>
    <Footer />
</template>

<style scoped>
</style>
