// src/components/Nav.vue
<template>
    <header class="fixed w-full z-20 top-0 left-0 border-b border-gray-700 bg-gray-900">
        <nav class="bg-gray-900 px-4 py-4 mx-auto max-w-screen-xl">
            <a href="/"><img src="src/assets/logo.svg" class="w-56" /></a>
        </nav>
    </header>
</template>

<script>
export default {
    
}
</script>

<style>
    
</style>

// src/Nav.jsx
function Nav() {
    return (
        <header className="fixed w-full z-20 top-0 left-0 border-b border-gray-700 bg-gray-900">
            <nav className="bg-gray-900 py-8 px-4 mx-auto max-w-screen-xl lg:py-4">
                <a href="/"><img src="src/assets/images/logo.svg" className="w-56" /></a>
            </nav>
        </header>
    )
}
export default Nav
